# Numpy

In [1]:
# Numpy 
# numpy is an opensource library that is used for scientific calculations

# Why Numpy is bettter than List?
# 1.Numpy has more advance functions as compare to list.
# 2.Numpy is Homogeneous(one type of datatype) data type while List is heterogenous datatype.
# 3.Numpy takes less memory as compare to List.
# 4.Numpy has less execution time as compare to List.

In [5]:
!pip install numpy

In [7]:
import numpy as np

In [9]:
a=[1,2,3]
type(a)

list

In [11]:
b=np.array(a)
b

array([1, 2, 3])

In [13]:
a=[[1,2,3],[6,5,8],[7,8,9]]
b=np.array(a)
b

array([[1, 2, 3],
       [6, 5, 8],
       [7, 8, 9]])

In [15]:
print("total rows and columns:", b.shape)

total rows and columns: (3, 3)


In [17]:
print("total Elements:" , b.size)

total Elements: 9


In [19]:
print("Dimension of an array:" , b.ndim)

Dimension of an array: 2


# how can we create a user defined array?

In [22]:
a=[]
size=int(input("enter size"))
for i in range(size):
    val=int(input("enter item:"))
    a.append(val)
b=np.array(a)
b

enter size 3
enter item: 23
enter item: 45
enter item: 67


array([23, 45, 67])

In [24]:
type(b)

numpy.ndarray

In [ ]:
'''
1.Matrix--->rows,columns
2.In matrix-->n(rows)=no.of(columns)--->Symmetric Matrix
3.In matrix n(rows)!=n(columns)--->Asymmetric Matrix
4.Digonal Elements--->[(1,1),(2,2),(3,3),......,(n,n)]
5.Images---->pixels--->(0-255)pixel---->normalize---->(0-1)
6.Optimization--->staring weights(m),bias(b) ramdomly selsct--->Numpy
functions.
'''

# Predefined Functions in Numpy

In [32]:
#(1).zeros:it will create an array in which all the elements are 0.

In [36]:
a=np.zeros(3)
a

array([0., 0., 0.])

In [40]:
b=np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [1]:
#(2.)ones()--->it will create an array in which all the elements are 1.

In [10]:
!pip install numpy

In [12]:
import numpy as np

In [20]:
a=np.ones(3)
a

array([1., 1., 1.])

In [14]:
b=np.ones((2,3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
#(3.)eye()---->it will create an array in which diagonal values wil be 1 and rest all are 0.

In [24]:
np.eye(3,4)   #Asymmetric Matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [26]:
np.eye(3)   #Symmetric Matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
#(4.) diag()--->using diag(),we can pass our custom array on diagonal position.

In [30]:
a=np.diag([1,2,56,89])
a

array([[ 1,  0,  0,  0],
       [ 0,  2,  0,  0],
       [ 0,  0, 56,  0],
       [ 0,  0,  0, 89]])

In [32]:
#(5.) Random Module
#(a)Randint(min_range,max_range,total_numbers)

In [34]:
np.random.randint(1,10,4)

array([5, 1, 4, 9])

In [40]:
a=np.random.rand(5)
a

array([0.53188288, 0.36323878, 0.70975879, 0.56142794, 0.2434867 ])

In [42]:
#seed()--->it will fix the data when it is generated.

In [48]:
np.random.seed(11)  #any random value in the bracket to fix the data
a=np.random.randint(1,10,3)
a

array([1, 2, 8])

# View vs Copy

In [53]:
a=np.array([10,20,30,40,50,60,70,80])
b=a[2:5]
b

array([30, 40, 50])

In [63]:
a=np.array([10,20,30,40,50,60,70,80])
b=a[2:5]
b[:]=0
b


array([0, 0, 0])

In [65]:
a=np.array([10,20,30,40,50,60,70,80])   #View-->original data me bhi change hojata hai
b=a[2:5]
b[:]=0
b
a

array([10, 20,  0,  0,  0, 60, 70, 80])

In [69]:
a=np.array([10,20,30,40,50,60,70,80])  #copy--->original data me change nhi hota hai
b=a[2:5].copy()
b[:]=0
b
a

array([10, 20, 30, 40, 50, 60, 70, 80])

# Reshaping the Array

In [72]:
#n(rows)*n(columns)=n(total_elements)

In [74]:
a=np.random.randint(1,100,12)
a

array([14, 77, 34, 72, 83, 25, 93, 49, 33, 46,  5, 35])

In [ ]:
'''
12--->
1*12,12*1
2*6,6*2
3*4,4*3
'''

In [76]:
a.reshape(2,6)

array([[14, 77, 34, 72, 83, 25],
       [93, 49, 33, 46,  5, 35]])

In [80]:
a.reshape(6,2)


array([[14, 77],
       [34, 72],
       [83, 25],
       [93, 49],
       [33, 46],
       [ 5, 35]])

In [82]:
a.reshape(3,4)

array([[14, 77, 34, 72],
       [83, 25, 93, 49],
       [33, 46,  5, 35]])

In [86]:
#error
# a.reshape(5,2)   #5*2=10 != no.of elements(12)

In [88]:
#1-60 bet total_36 elements

In [90]:
a=np.random.randint(1,60,36)
a

array([13,  2, 11, 38, 54, 40, 21, 18, 28, 25, 57, 18,  4,  7, 44, 51, 51,
        1, 16, 33, 24, 28,  7, 26, 44, 11, 58, 28, 45, 54, 15,  8, 56, 16,
        1, 41])

In [92]:
a.reshape(6,6)

array([[13,  2, 11, 38, 54, 40],
       [21, 18, 28, 25, 57, 18],
       [ 4,  7, 44, 51, 51,  1],
       [16, 33, 24, 28,  7, 26],
       [44, 11, 58, 28, 45, 54],
       [15,  8, 56, 16,  1, 41]])

In [94]:
a.reshape(12,3)

array([[13,  2, 11],
       [38, 54, 40],
       [21, 18, 28],
       [25, 57, 18],
       [ 4,  7, 44],
       [51, 51,  1],
       [16, 33, 24],
       [28,  7, 26],
       [44, 11, 58],
       [28, 45, 54],
       [15,  8, 56],
       [16,  1, 41]])

# Conditional Selection in Numpy

In [99]:
a=np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [101]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [103]:
b=a>10
a[b]

array([11, 12, 13, 14, 15])

In [105]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [107]:
a=np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [109]:
b=np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [111]:
a+b

array([[ 6,  8],
       [10, 12]])

In [113]:
a-b

array([[-4, -4],
       [-4, -4]])

In [115]:
a.dot(b)   #for multiplication

array([[19, 22],
       [43, 50]])

In [1]:
#(6.) linespace--->it will create an array in which gap of two values will be equal.

In [5]:
!pip install numpy

In [7]:
import numpy as np

In [11]:
a= np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [13]:
# (7.)unique()---->it will create an array in which we have original values.
#it will return 3 arrays.
#1.arr : using unique values of array.
#2.return_index=True

In [15]:
#np.unique(arr , return_index=True,return_counts= True)

In [17]:
a=np.array([1,2,2,2,3,4,3,5,4,6,7,6,6,7,9])
np.unique(a, return_index=True, return_counts=True)

(array([1, 2, 3, 4, 5, 6, 7, 9]),
 array([ 0,  1,  4,  5,  7,  9, 10, 14], dtype=int64),
 array([1, 3, 2, 2, 1, 3, 2, 1], dtype=int64))

In [19]:
a=np.random.randint(1,10,9).reshape(3,3)
a

array([[5, 3, 5],
       [1, 7, 8],
       [2, 2, 2]])

In [25]:
np.sum(a,axis=0)

array([ 8, 12, 15])

In [27]:
np.sum(a,axis=1)

array([13, 16,  6])

# Hstack and Vstack

In [30]:
a=np.arange(1,5)
a

array([1, 2, 3, 4])

In [34]:
b=np.arange(5,9)
b

array([5, 6, 7, 8])

In [36]:
c=np.arange(9,13)
c

array([ 9, 10, 11, 12])

In [38]:
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [40]:
np.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])