In [1]:
import numpy as np
import pandas as pd 

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [2]:
df = pd.read_csv("covid_toy.csv")

In [3]:
df.head(2)

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,Mild,Kolkata,No
1,27,Male,100.0,Mild,Delhi,Yes


In [4]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [5]:
from sklearn.model_selection import train_test_split

x_train , x_test , y_train ,y_test = train_test_split(df.drop(
    columns = ['has_covid']) , df['has_covid'] , test_size = 0.2)

In [6]:
x_train

,age,gender,fever,cough,city
44,20,Male,102.0,Strong,Delhi
19,42,Female,NaN,Strong,Bangalore
91,38,Male,NaN,Mild,Delhi
52,47,Female,100.0,Strong,Bangalore
88,5,Female,100.0,Mild,Kolkata
...,...,...,...,...,...
22,71,Female,98.0,Strong,Kolkata
48,66,Male,99.0,Strong,Bangalore
21,73,Male,98.0,Mild,Bangalore
59,6,Female,104.0,Mild,Kolkata


# Manually type output

In [8]:
#adding simple imputer to fever column
si =SimpleImputer(strategy = 'mean')
x_train_fever = si.fit_transform(x_train[['fever']])

#also the test data
x_test_fever = si.fit_transform(x_train[['fever']])

x_train_fever.shape

(80, 1)

In [9]:
#ordinal encoding -->Cough

oe = OrdinalEncoder(categories = [['Mild' , 'Strong']])
x_train_cough = oe.fit_transform(x_train[['cough']])

#also the test data
x_test_cough = oe.fit_transform(x_test[['cough']])

x_train_cough.shape

(80, 1)

In [16]:
#OneHotEncoding ---> Gender , city

ohe = OneHotEncoder(drop = 'first', sparse_output = False)
x_train_gender_city = ohe.fit_transform(x_train[['gender' , 'city']])

#also the test data
x_test_gender_city = ohe.fit_transform(x_train[['gender' , 'city']])

x_train_gender_city.shape

(80, 4)

In [20]:
#Extracting Age

x_train_age = x_train.drop(columns = 
                           ['gender' , 'fever','cough','city']).values

#also the test data

x_test_age = x_test.drop(columns = 
                         ['gender' , 'fever','cough','city']).values


In [22]:
x_train_age.shape

(80, 1)

In [24]:
x_train_transformed=np.concatenate((x_train_age,x_train_fever,
                                    x_train_gender_city,
                                    x_train_cough),axis=1)

In [26]:
#x_test_transformed=np.concatenate((x_test_age,
#                                  x_test_fever,
 #                                  x_test_gender_city,
  #                                 x_test_cough),axis=1)

In [28]:
x_train_transformed.shape

(80, 7)

# BY THE HELP OF COLUMN TRANSFORMER

In [31]:
# A Column Transformer in advanced Python (commonly used in machine learning) allows you to apply different preprocessing 
# steps to different columns of your data. It is part of the scikit-learn library and is especially useful when dealing 
# with datasets that contain both numerical and categorical data.

# Why Use a Column Transformer?
# Different columns may need different preprocessing (e.g., scaling numeric data while encoding categorical data).
# It allows you to handle preprocessing in a clean, efficient, and pipeline-compatible way.

# How Does It Work?
# You specify transformations (e.g., scaling, encoding) and the columns to which they should be applied.
# It applies each transformation to the specified columns and combines the results.

In [33]:
from sklearn.compose import ColumnTransformer  # this is how to import ColumnTransformer

transformer = ColumnTransformer(transformers=[
    ('tnf1', SimpleImputer(), ['fever']),  # in a 'fever' column by the help of SI
    # fill missing values by mean, median, mode.
    ('tnf2', OrdinalEncoder(categories=[['Mild', 'Strong']]), ['cough']),  # by this process we encode our data
    ('tnf3', OneHotEncoder(sparse_output=False, drop='first'), ['gender', 'city'])
], remainder='passthrough')  # remainder = passthrough ==> it means rest all the columns remain same.

In [35]:
transformer.fit_transform(x_train).shape

(80, 7)

In [37]:
transformer.fit_transform(x_test).shape

(20, 7)

In [83]:
df = pd.read_csv("insurance.csv")

In [85]:
df.head(5)

,age,sex,bmi,children,smoker,region,charges
0,19,female,27.900,0,yes,southwest,16884.92400
1,18,male,33.770,1,no,southeast,1725.55230
2,28,male,33.000,3,no,southeast,4449.46200
3,33,male,22.705,0,no,northwest,21984.47061
4,32,male,28.880,0,no,northwest,3866.85520


In [87]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [89]:
df = pd.get_dummies(df , columns=['smoker' , 'sex','region'] ,drop_first = True)
df.astype(int)

,age,bmi,children,charges,smoker_yes,sex_male,region_northwest,region_southeast,region_southwest
0,19,27,0,16884,1,0,0,0,1
1,18,33,1,1725,0,1,0,1,0
2,28,33,3,4449,0,1,0,1,0
3,33,22,0,21984,0,1,1,0,0
4,32,28,0,3866,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...
1333,50,30,3,10600,0,1,1,0,0
1334,18,31,0,2205,0,0,0,0,0
1335,18,36,0,1629,0,0,0,1,0
1336,21,25,0,2007,0,0,0,0,1


In [99]:
df = pd.read_csv("insurance.csv")

In [101]:
ohe = OneHotEncoder()

In [103]:
ohe = OneHotEncoder(drop = 'first' ,sparse_output = False , dtype = np.int32)

In [105]:
df = ohe.fit_transform(df[['sex','region','smoker']])

In [107]:
df

array([[0, 0, 0, 1, 1],
       [1, 0, 1, 0, 0],
       [1, 0, 1, 0, 0],
       ...,
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 1, 0, 0, 1]])

In [ ]:








The FunctionTransformer is a tool in scikit-learn, a popular Python library
for machine learning, that allows you to apply a specified function to the input
data. The FunctionTransformer can be useful for performing custom 
transformations of input data in a machine learning pipeline.
'''

In [80]:
#The FunctionTransformer takes as input a single function that will be applied to each sample in the data.
#This function can be any Python function that takes a single argument, such as a lambda function or a user-defined function.
#The function should return the transformed sample.

In [82]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

# create a dataset
X = np.array([[1, 2], [3, 4]])

# define the transformation function
log_transform = FunctionTransformer(np.log1p)

# apply the transformation to the dataset
X_transformed = log_transform.transform(X)

# view the transformed data
print(X_transformed)

[[0.69314718 1.09861229]
 [1.38629436 1.60943791]]


In [89]:
#practical usecases
# 1.Custom Feature Engineering

from sklearn.preprocessing import FunctionTransformer
import numpy as np

#create a dataset
X=np.array([[1, 2], [3, 4]])

#define a custom feature engineering function

def geet(X):
    return np.hstack((X,X**2))

# create a FunctionTransformer to apply the custom function
custom_transformer = FunctionTransformer(geet)


# apply the transformer to the input data
X_transformed = custom_transformer.transform(X)

# view the transformed data
print(X_transformed)


[[ 1  2  1  4]
 [ 3  4  9 16]]


In [91]:
#eg:Scaling And Normalization

from sklearn.preprocessing import FunctionTransformer
import numpy as np

#create a dataset
X=np.array([[1, 2], [3, 4]])

#define a custom feature engineering function

def my_scaling(X):
    return X / np.max(X)

# create a FunctionTransformer to apply the custom function
custom_transformer = FunctionTransformer(my_scaling)


# apply the transformer to the input data
X_transformed = custom_transformer.transform(X)

# view the transformed data
print(X_transformed)


[[0.25 0.5 ]
 [0.75 1.  ]]


In [93]:
# 3.Data Cleaning

from sklearn.preprocessing import FunctionTransformer
import numpy as np

#create a dataset
X=np.array([[1, 2], [3, np.nan]])

#define a custom feature engineering function

def my_cleaning(X):
    X[np.isnan(X)] = 0
    return X

# create a FunctionTransformer to apply the custom function
custom_transformer = FunctionTransformer(my_cleaning)


# apply the transformer to the input data
X_transformed = custom_transformer.transform(X)

# view the transformed data
print(X_transformed)

[[1. 2.]
 [3. 0.]]


# REAL LIFE USE-CASE OF FUNCTION TRANSFORMER

In [96]:
import numpy as np
import pandas as pd

In [98]:
df = pd.read_csv('placement.csv')

In [100]:
df.head(2)

,cgpa,resume_score,placed
0,8.14,6.52,1
1,6.17,5.17,0


In [102]:
from sklearn.preprocessing import FunctionTransformer

In [104]:
x=df.drop(columns = ['placed'])
y=df['placed']


In [106]:
log_transform = FunctionTransformer(np.log1p)

# apply the transformation to the dataset
X_transformed = log_transform.transform(x)

In [113]:
X_transformed

,cgpa,resume_score
0,2.212660,2.017566
1,1.969906,1.819699
2,2.226783,2.288486
3,2.064328,2.112635
4,2.142416,2.116256
...,...,...
95,1.991976,1.998774
96,2.222459,2.170196
97,2.034706,2.172476
98,2.212660,1.891605
